#include<stdio.h>
#include<stdlib.h>
//Creatinganode
structnode{
intvalue;
structnode*next;
}
//printthelinkedlistvalue
voidprintLinkedlist(structnode*p){
while(p!=NULL){
printf("%d",p->value);
p=p->next;
}
}
intmain(){
//Initializenodes
structnode*head;
structnode*one=NULL;
structnode*two=NULL;
structnode*three=NULL;
//Allocatememory
one=malloc(sizeof(structnode));
two=malloc(sizeof(structnode));
three=malloc(sizeof(structnode));
//Assignvaluevalues
one->value=1;
two->value=2;
three->value=3;
//Connectnodes
one->next=two;
two->next=three;
three->next=NULL;
//printingnode-value
head=one;
printLinkedlist(head);
}
